version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Expose Nginx to the public on port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount your custom nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - monitoring

  backend:
    image: mnikkilla/backend:latest
    ports:
      - "8001:8001"
    networks:
      - monitoring
    environment:
      - FLASK_ENV=production

  frontend:
    image: mnikkilla/frontend:latest
    ports:
      - "3001:80"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - monitoring
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

networks:
  monitoring:
    driver: bridge
