version: '3.8'

services:
  backend:
    image: saeidnkh/backend:latest  # Use the 'latest' tag from Docker Hub
    ports:
      - "8001:8001"
    networks:
      - monitoring
    environment:
      - FLASK_ENV=production

  frontend:
    image: saeidnkh/frontend:latest  # Use the 'latest' tag from Docker Hub
    ports:
      - "3001:80"  # Expose the frontend on port 3001 (can be changed to 80)
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - "/d/Saeid/wiley/New folder/SLO-Monitoring-Dashboard/backend/prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - monitoring
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

networks:
  monitoring:
    driver: bridge
